/**
 * @file pwm.h
 * @brief High-level buzzer control API using PWM (TIM1).
 *
 * This file provides a high-level, non-blocking API for controlling
 * a buzzer using PWM generated by TIM1.
 *
 * The API allows:
 *  - Setting buzzer frequency and duty cycle
 *  - Generating periodic sound patterns (ON/OFF beeping)
 *  - Non-blocking operation via a simple state machine
 *
 * Timing is handled by calling Buzzer_Update() periodically
 * (typically every 1 ms).
 *
 * This module relies on the TIM1 PWM API and does not access
 * hardware registers directly
 * 
 * @date 2026-02-04 
 */

#ifndef PWM_H
#define PWM_H

#include <stdint.h>

/**
 * @brief Initializes the buzzer PWM subsystem.
 *
 * Configures TIM1 to generate PWM on the selected channel.
 * The buzzer is initially disabled (duty cycle = 0).
 *
 * @param channel    TIM1 PWM channel number.
 * @param period     PWM period value.
 * @param prescaler  TIM1 prescaler value.
 */
void Buzzer_Init(uint8_t channel, uint16_t period, uint16_t prescaler);

/**
 * @brief Starts periodic buzzer operation.
 *
 * Initializes the internal state machine and enables
 * periodic ON/OFF sound generation.
 *
 * @param freq     PWM frequency in Hz.
 * @param duty     PWM duty cycle value.
 * @param on_ms    Buzzer ON time in milliseconds.
 * @param off_ms   Buzzer OFF time in milliseconds.
 *
 * @note The function Buzzer_Update() must be called periodically
 *       with a fixed time base (e.g. every 1 ms).
 */
void Buzzer_Start(uint16_t freq, uint16_t duty, uint16_t on_ms, uint16_t off_ms);

/**
 * @brief Updates the buzzer state machine.
 *
 * Controls the ON/OFF timing of the buzzer based on
 * the configured durations.
 *
 * This function is non-blocking and must be called
 * periodically with a constant time interval.
 */
void Buzzer_Update(void);

/**
 * @brief Stops buzzer operation.
 *
 * Disables PWM output and stops the timer.
 * The internal state is reset to OFF.
 */
void Buzzer_Stop(void);

#endif
